# Generated by Django 3.0.6 on 2020-06-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_id'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='dorsal',
            new_name='jersey',
        ),
    ]
