# Generated by Django 3.0.6 on 2020-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0003_auto_20200601_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
