# Generated by Django 3.0.6 on 2020-06-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0005_auto_20200603_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseManager.Team'),
        ),
    ]
