# Generated by Django 3.0.6 on 2020-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0007_auto_20200610_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='field_goals_miss_per_game',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=65),
        ),
        migrations.AddField(
            model_name='player',
            name='free_throws_miss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='free_throws_miss_per_game',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=65),
        ),
        migrations.AddField(
            model_name='player',
            name='three_points_field_goals_miss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='conceded_free_throws_miss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='conceded_three_points_field_goals_miss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='field_goals_miss_per_game',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=65),
        ),
        migrations.AddField(
            model_name='team',
            name='free_throws_miss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='free_throws_miss_per_game',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=65),
        ),
        migrations.AddField(
            model_name='team',
            name='three_points_field_goals_miss',
            field=models.IntegerField(default=0),
        ),
    ]
