# Generated by Django 3.0.6 on 2020-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0008_auto_20200611_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='information_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
