# Generated by Django 3.0.6 on 2020-08-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0010_defendinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefendInfo',
        ),
    ]
