# Generated by Django 3.0.6 on 2020-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0011_delete_defendinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
