# Generated by Django 3.0.6 on 2020-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0012_player_is_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cluster',
            field=models.IntegerField(default=-1),
        ),
    ]
