# Generated by Django 3.0.6 on 2020-08-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0015_auto_20200811_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shotchart',
            old_name='pf',
            new_name='chart_pk',
        ),
    ]
