# Generated by Django 3.0.6 on 2020-08-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0016_auto_20200811_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerShotCharts',
            fields=[
                ('chart_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('scatter_chart', models.ImageField(upload_to='./uploaded_media', verbose_name='Scatter shot chart')),
                ('hexbin_chart', models.ImageField(upload_to='./uploaded_media', verbose_name='Hexbin shot chart')),
            ],
        ),
        migrations.DeleteModel(
            name='ShotChart',
        ),
    ]
