# Generated by Django 3.0.6 on 2020-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseManager', '0021_auto_20200817_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playershotcharts',
            name='hexbin_chart',
            field=models.ImageField(upload_to='', verbose_name='Hexbin shot chart'),
        ),
        migrations.AlterField(
            model_name='playershotcharts',
            name='scatter_chart',
            field=models.ImageField(upload_to='', verbose_name='Scatter shot chart'),
        ),
    ]
